[workspace]
members = [
    "crates/frameark-api",
    "crates/frameark-core",
    "crates/frameark-discovery",
    "crates/frameark-ffi",
]
resolver = "3"

[workspace.package]
authors = ["FrameArk contributors"]
edition = "2024"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/kairowan/FrameArk"
rust-version = "1.97"
version = "0.1.0"

[workspace.dependencies]
frameark-core = { path = "crates/frameark-core" }
mdns-sd = { version = "0.21.5", default-features = false }
jni = "0.21.1"

[workspace.lints.rust]
unsafe_code = "deny"
